### PR TITLE
Search beatmaps by hash

### PR DESCRIPTION
**Pull request by BaliBalo**
## Proposed Changes
I have a tool relying on the search by hash that beatsaver used to offer (useful to connect with scoresaber). This very simple PR adds it back.

## Platforms
This pull request modifies: *(select all that apply)*
- [ ] Client
- [x] Server

## Types of Changes
This pull request is contains: *(select all that apply)*
- [ ] Bug fixes *(non-breaking change which fixes an issue)*
- [x] New features *(non-breaking change which adds functionality)*
- [ ] Breaking changes *(fix or feature that would cause existing functionality to not work as expected)*

## Checklist
- [x] I have read the [contribution guidelines](https://github.com/lolPants/beatsaver-reloaded/blob/master/.github/CONTRIBUTING.md)
- [x] I have checked the changes adhere to the project's style guide and all tests pass
- [x] I have (to the best of my ability) checked for vulnerabilities, or any ways that my code could be abused and concluded that it is safe to run in production

## Further Comments
I understand that the new version is taking a lot of effort and this might not be the priority. Hopefully that helps out.

### CODE REVIEW

**Comment by Kylemc1413** [comment]
I believe that already exists in /api/maps/by-hash/

**Comment by Assistant** [comment]
https://github.com/lolPants/beatsaver-reloaded/blob/231427d0b2e27b99141cbc3c24332f8a2c604e7a/server/src/routes/maps.ts#L183

**Comment by BaliBalo** [comment]
Woops. I need to learn how to search better. Thanks.

**Comment by lolPants** [comment]
As a further clarification as to why it was moved away from being a `/search` endpoint, hashes are (and always have been) unique on BeatSaver so it didn't make much sense to report more than one.

Before it would return an empty array or an array of 1 map, now it returns one map or a 404.

**Pull request closed without merging**
